### ISSUE TITLE
Add code minify

### ISSUE THREAD

**Issue by RiceWithMeat** [siberiacancode/mock-config-server#65]
Add code minifying for reduce bundle size

**Comment by MiaInturi** [comment]
"reduce bundle size" does not apply to mock-config-server package because we does not bundled code — we just transpile code to needed ES version. I think that bundle/minification of source code of mock-config-server package is not necessary becase of that package runs only in nodejs enviroment which has direct access to node_modules (no need for http requests).
Instead of bundling package i suggest using babel and make package available for lower versions of nodejs.
